---
- name: SSH | disable root auth and passwd auth
  shell:
          cmd: | 
            cat <<EOF > /etc/ssh/sshd_config.d/00-setup.conf
            PermitRootLogin no
            PasswordAuthentication no
            PubkeyAuthentication yes
            ChallengeResponseAuthentication no
            EOF
  notify:
    - restart-ssh